plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'db/*_schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'config/environments/*.rb'
    - 'config/initializers/*'
    - 'spec/**/*'
    - 'test/**/*'

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/FirstParameterIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/TrailingEmptyLines:
  Enabled: true

Metrics/MethodLength:
  Max: 20
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/StringLiterals:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal

Rails:
  Enabled: true
Rails/OutputSafety:
  Enabled: true
Rails/SkipsModelValidations:
  Exclude:
    - 'db/seeds.rb'
